version: '3.7'

services:
  http:
    image: nginx:latest
    ports:
      - "${HTTP_PORT:-8080}:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php
    restart: on-failure

  php:
    build: docker/php
    volumes:
      - ./:/var/www
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "${DB_PORT_EXT:-3306}:3306"
    volumes:
      - db:/var/lib/mysql
      - ./:/var/www
    environment:
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_DATABASE: "${DB_DATABASE}"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

volumes:
  db:
